name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
   workflow_dispatch:
#  push:
#    branches:
#      - master
#    paths:
#      - 'server/**'

jobs:
  build-it:
    runs-on: ubuntu-latest
    steps:
#      - name: Get latest tag
#        id: vars
#        run: echo ::set-output name=tag::${GITHUB_REF:10}

#      - name: Clone repository
#        uses: actions/checkout@v2
#        with:
#          ref: ${{ steps.vars.outputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
#          context: "{{defaultContext}}:server"
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ GITHUB.REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
